ALTER TABLE employees ADD FOREIGN KEY (MANAGER_ID)
  REFERENCES employees (EMPLOYEES_ID);

ALTER TABLE employees ADD FOREIGN KEY (JOB_ID)
  REFERENCES jobs (JOB_ID);

ALTER TABLE employees ADD FOREIGN KEY (DEPARTMENT_ID)
  REFERENCES departments (DEPARTMENT_ID);

ALTER TABLE departments ADD FOREIGN KEY (LOCATION_ID)
    REFERENCES locations (LOCATION_ID);