CREATE TABLE LOCATIONS (
  LOCATION_ID INT(8) AUTO_INCREMENT PRIMARY KEY,
  STREET_ADRESS VARCHAR (12);
  POSTAL_CODE  VARCHAR(12),
  CITY VARCHAR(30) NOT NULL,
  STATE_PROVINCE VARCHAR(25)
);
CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID INT(8) AUTO_INCREMENT PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR(30),
  LOCATION_ID INT
);
CREATE TABLE JOBS(
  JOB_ID INT AUTO_INCREMENT PRIMARY KEY ,
  JOB_TITLE VARCHAR(35) NOT NULL ,
  MIN_SALARY INT(6),
  MAX_SALARY INT(6)
);
CREATE TABLE EMPLOYEES(
  EMPLOYEES_ID INT AUTO_INCREMENT PRIMARY KEY ,
  FIRST_NAME VARCHAR(20),
  LAST_NAME VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(20) NOT NULL,
  PHONE_NUMBER VARCHAR(20),
  HIRE_DATE DATE NOT NULL,
  JOB_ID INT(10) NOT NULL,
  SALARY DECIMAL(8,2),
  COMMISSION_PCT DECIMAL(2,2),
  MANAGER_ID INT,
  DEPARTMENT_ID INT
);


